server:
  port: 0
  error:
    include-message: always
spring:
  application:
    name: alarm-service
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  sendgrid:
    api-key: ${SENDGRID_MOIZA}

email:
  from: test123@test.com

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

token:
  expiration_time: 21600000 # 60 * 60 * 6 * 1000=> 6시간
  secret: testtoken # TODO 설정 파일 보안정보 옮기기